### ISSUE TITLE
Docker image unavailable (server returning 403)

### ISSUE THREAD

**Issue by jdhutchison** [mautrix/imessage#108]
Hi, not sure if this is the best channel to notify you of the issue but it looks like there's an issue with your Docker repository on dock.mau.dev. Trying to pull an image (I'm after imessage but it looks to be an issue when trying to get any image) results in a 403:

```
# docker pull dock.mau.dev/mautrix/imessage:latest
Error response from daemon: Head "https://dock.mau.dev/v2/mautrix/imessage/manifests/latest": denied: access forbidden
```

Also, just wanted to say I really appreciate your Matrix bridges - they've been incredibly helpful.

**Comment by tulir** [comment]
You can't run iMessage in docker
