### ISSUE TITLE
Backfill doesn't backfill messages on a self-hosted instance

### ISSUE THREAD

**Issue by ownaginatious** [mautrix/imessage#122]
When running `mautrix-imessage` on a machine with SIP enabled, backfilling only creates rooms, but does not actually populate them with any messages.

A lot of log lines like this are seen:

```
2023-09-13T22:38:34-07:00 DBG Dropping backfill bridge-initial-+<redacted>::1694669914213 as Beeper batch sending is not supported portal_guid=iMessage;-;+<redacted>
```

Commenting out [this](https://github.com/mautrix/imessage/blob/master/historysync.go#L215-L218) block fixes it. Condition is probably incorrect?

**Comment by sumnerevans** [comment]
History sync is only supported in Beeper because Synapse removed support for batch sending

**Comment by ownaginatious** [comment]
@sumnerevans but then why did commenting out the lines fix it in my case? I’m using the latest maunium synapse docker image, for context. Is it still supported in that fork?

Either way, if it’s no longer supported, it should probably be more clearly stated to avoid confusion for those self hosting 😅
