### ISSUE TITLE
[bluebubbles] Implement GetMessagesBetween

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#136]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR47

**Comment by trek-boldly-go** [comment]
@cnuss seems to have completed this implementation. Will close this issue, but new issues can be raised if a problem arises later.
