### ISSUE TITLE
[bluebubbles] Implement GetMessagesWithLimit

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#138]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR55

**Comment by trek-boldly-go** [comment]
Complete with https://github.com/mautrix/imessage/commit/e25674a3452edbf78420aa92f26de9b3d83cf913
