### ISSUE TITLE
[bluebubbles] Implement GetChatsWithMessagesAfter

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#140]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR63

**Comment by trek-boldly-go** [comment]
Basic implementation complete, needs tested. Bluebubbles didn't have a date filter on the endpoint I used, so this will iterate over the endpoint and results to keep adding more chats as long as the lsmd property is still after the minDate parameter.

**Comment by trek-boldly-go** [comment]
closing this as the current implementation is working, even though it could be improved in the future.
