### ISSUE TITLE
[bluebubbles] Implement GetChatInfo

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#143]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR103

**Comment by trek-boldly-go** [comment]
@cnuss I see you have added some code for both of these functions. Is it safe to close this issue? There is always room for improvement later, but if it works then it works (in my book at least).

**Comment by cnuss** [comment]
I added a private function but the public function that transposes the BB API into the internal `imessage` Struct still needs to be written (`getChatInfo` [done] vs `GetChatInfo` [not done])

**Comment by trek-boldly-go** [comment]
Actually I think you already connected the two from what I can tell:
<img width="762" alt="image" src="https://github.com/mautrix/imessage/assets/66212896/80f03570-df93-4ac1-85f6-2210b92f022c">

**Comment by cnuss** [comment]
my memory failed me! I think I was thinking of GetChatMessage 

closing!
