### ISSUE TITLE
[bluebubbles] Implement SendMessage

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#145]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR111

**Comment by trek-boldly-go** [comment]
Basic implementation complete, needs tested and could be enhanced with replyToPart support.

**Comment by trek-boldly-go** [comment]
After setting up the webhook functionality, I was able to test this SendMessage function and it didn't work. I am not sure what is causing it without further investigation. I'll remove myself from this issue for the time being in case someone else wants to pick it up.

**Comment by trek-boldly-go** [comment]
Completed with commit https://github.com/mautrix/imessage/commit/1f518318564f7548f7dc708e5e9ab4ddf35b1cba which adds support for sending replies from matrix to BlueBubbles.
