### ISSUE TITLE
[bluebubbles] Implement SendFile

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#146]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR115

**Comment by trek-boldly-go** [comment]
So I have a super basic version of this done, but bluebubbles doesn't support sending text and the attachment in the same call. So I will need to add a second request to also send the text, then a [third request that links them together](https://documenter.getpostman.com/view/765844/UV5RnfwM#90ef6611-9f9c-41eb-b915-9a405be51406) (I think).

**Comment by cnuss** [comment]
we've had a handful of tries at this but my most recent commits show promise:
 - https://github.com/mautrix/imessage/commit/bd6b0a7e89ad21d55c75f0291a4da0aae0a8bfa7
 - https://github.com/mautrix/imessage/commit/f81d3a773af3ede6377528bd93ded7fa29dce619
 
 closing this and we'll open a new issue if we find bugs
