### ISSUE TITLE
[bluebubbles] Implement ResolveIdentifier

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#150]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR135

**Comment by trek-boldly-go** [comment]
I have an implementation of this that works, but it doesn't really do any validation. It looks for an `@` symbol, and if it doesn't find it, it scrubs all non-numeric chars, then prepends `iMessage;-;+` to the number. If it finds the `@` symbol, it doesn't do any cleanup and prepends `iMessage;-;` (notice the lack of `+`). More validation runs the risk of failure on valid use cases, so this implementation is probably the best option for now.
