### ISSUE TITLE
[bluebubbles] Implement CreateGroup

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#153]
https://github.com/mautrix/imessage/commit/c314edf39987a4f30064e16dc30ded206db02ca0#diff-add0e027970853876947ede515fd2419541057010ed0cfb334f30219fcd9979fR143

**Comment by trek-boldly-go** [comment]
Creating groups requires a first message to be sent. There isn't a good way to allow users to input all the numbers and a first message as a bot command (how would a user denote the last address and the start of the message? So this function will remain unsupported.
