### ISSUE TITLE
[bluebubbles] Implement handleGroup[Name|Icon][Changed|Removed]

### ISSUE THREAD

**Issue by cnuss** [mautrix/imessage#164]

**Comment by trek-boldly-go** [comment]
Group name updates work correctly. Group icons added or changed work, but removing an icon is not supported by the underlying bridge so it cannot be supported at this time. https://github.com/mautrix/imessage/blob/c296acaac61b9f81551e9a9eaba30815425fb84c/portal.go#L1637C1-L1650C2
