### ISSUE TITLE
Crash when getting group avatar

### ISSUE THREAD

**Issue by ChaseThomas** [mautrix/imessage#172]
Logs below, with some identifiers and memory addresses removed

2024-01-23T20:04:30-05:00 DBG Received incoming message identifier in iMessage;+;<chat_identifier> () module=iMessage
2024-01-23T20:04:30-05:00 INF Creating Matrix room to handle message portal_guid=iMessage;+;<chat_identifier>
2024-01-23T20:04:30-05:00 DBG Getting chat info to create Matrix room portal_guid=iMessage;+;<chat_identifier>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1055ce288]

goroutine 104 [running]:
go.mau.fi/mautrix-imessage/imessage/bluebubbles.(*blueBubbles).GetGroupAvatar(<memory_address>, {<memory_address>, <memory_address>})
	<project_directory>/imessage/bluebubbles/api.go:614 +0x98
main.(*Portal).CreateMatrixRoom(<memory_address>, <memory_address>, <memory_address>)
	<project_directory>/portal.go:837 +0x2f4
main.(*iMessageHandler).HandleMessage(<memory_address>, <memory_address>)
	<project_directory>/imessage/imessage.go:198 +0x358
main.(*iMessageHandler).Start(<memory_address>)
	<project_directory>/imessage/imessage.go:56 +0x294
created by main.(*IMBridge).Start in goroutine 1
	<project_directory>/imessage/main.go:536 +0x5f0
Bridge exited
exit status 2

**Comment by cnuss** [comment]
experienced the same problem, pushing a fix in my next commit tonight

**Comment by ChaseThomas** [comment]
Thank you for all your work!
