### ISSUE TITLE
bluebubbles - fuzzy matching on last 3 digits of phone number so matching incorrect contacts, esp w/ sms shortcodes

### ISSUE THREAD

**Issue by keithah** [mautrix/imessage#174]
So I have some SMS shortcode thing that sends me 'things to do' over text. The number is 88438. In BlueBubbles its showing up at someones contact, I looked them up in contacts in BB and the last 3 digits are '438' of their phone number..

![image](https://github.com/mautrix/imessage/assets/684920/acd7dee6-57fa-4da9-ae7c-061eb5633e93)

<img width="527" alt="image" src="https://github.com/mautrix/imessage/assets/684920/79e114b0-3294-4695-a74a-6d38b3c02bb3">
<img width="417" alt="image" src="https://github.com/mautrix/imessage/assets/684920/752a5d0f-503b-4a06-805c-cf4fed8bfa92">

**Comment by keithah** [comment]
BTW: I did verify in blue bubbles android client, this does not happen, its only in beeper via this bridge, and I spoke w/ the Bluebubbles folk and they confirmed that its in this client/bridge.

**Comment by trek-boldly-go** [comment]
Please try again with the code on branch `feat/improved-contact-matching`
This should use the same logic that the BlueBubbles clients do. Report back if it works/fails so I know to merge.

**Comment by keithah** [comment]
It looks good! I briefly have tested with 4 shortcakes that resolved to weird ppl, and they all come up as the normal shortcode now. thank you!

**Comment by trek-boldly-go** [comment]
Will be closed by #177
