### ISSUE TITLE
[BlueBubbles] Receiving read receipts from iMessage users

### ISSUE THREAD

**Issue by bigmalletman** [mautrix/imessage#195]
ROADMAP.md mentions that read receipts Matrix → iMessage and iMessage → Matrix are supported for BlueBubbles, but it appears that this has not been implemented on the Bluebubbles bridge. I am not receiving read receipts when iMessage users read my messages. These do appear properly in MacOS Message and the Bluebubbles Android app. However, they do not appear in Beeper Cloud Desktop or Android. These also do not appear in element.io web app.

I am unsure if this is a bug or an enhancement, since the ROADMAP.md implies this feature is already implemented.

bluebubbles android: ![bluebubblesandroid](https://github.com/mautrix/imessage/assets/9523991/00a7f7a9-e73f-4821-9d94-848384bb83a1)

macos messages: ![MacOSMessages](https://github.com/mautrix/imessage/assets/9523991/1072b92f-1ac1-4a5c-b036-1c94dca0eaaa)

beeper desktop: ![beeperdesktop](https://github.com/mautrix/imessage/assets/9523991/2155ebb7-2341-4cb3-9109-f1f396a697ec)

element web: ![elementweb](https://github.com/mautrix/imessage/assets/9523991/023f11e7-111d-4470-aa6b-0843b4836f21)
beeper android: ![beeperandroid](https://github.com/mautrix/imessage/assets/9523991/5481fa7f-ba9f-4193-ab25-3b35c9cb9f28)

**Comment by brewcrew87** [comment]
Just tagging along.  I am having the same issue.  The read receipt appears everywhere except for the actual Beeper app when using the BB connector.
