### ISSUE TITLE
Send messages/attachments with Private API

### ISSUE THREAD

**Issue by mehapps** [mautrix/imessage#218]
When sending messages or attachments, they should be sent w Private API for faster send (afaik they currently aren't, but correct me if i'm wrong)

**Comment by joshuafhiggins** [comment]
> When sending messages or attachments, they should be sent w Private API for faster send (afaik they currently aren't, but correct me if i'm wrong)

They do send with private-api, if the BlueBubbles server has it enabled. If you've changed the setting in BlueBubbles, you'll have to restart the Matrix bridge.
