### ISSUE TITLE
iMessage contacts don't show up in Element

### ISSUE THREAD

**Issue by ameyp** [mautrix/imessage#69]
In the console log of the bridge, I see:

```
[Jun  4, 2022 22:01:40] [iMessage/Mac/INFO] Contact access is allowed
```

However, when I attempt to start a chat with one of my iMessage contacts (by typing a part of their name) from Element, no suggestions show up.

**Comment by tulir** [comment]
Contacts aren't expected to show up, and starting chats isn't supported that way anyway. Existing chats with recent messages ([limit in the config](https://github.com/mautrix/imessage/blob/master/example-config.yaml#L94-L95)) will be synced on startup.

**Comment by ameyp** [comment]
Is this is a limitation of Matrix or of the bridge?
