### ISSUE TITLE
Matrix server linked in docs times out

### ISSUE THREAD

**Issue by ameyp** [mautrix/imessage#70]
The [doc](https://docs.mau.fi/bridges/go/imessage/index.html) links to https://matrix.to/#/#imessage:maunium.net, but when I attempt to connect to it using Element, I get an HTTP response saying that the gateway timed out.

**Comment by tulir** [comment]
That's probably an issue on your server, check the server logs first. If it looks like the server failed to connect, then I need at least the server name and time of attempt to check my logs.
