### ISSUE TITLE
Fatal Error, homeserver outdated, but server is the latest build

### ISSUE THREAD

**Issue by dhruvm-daimon** [mautrix/imessage#87]
I'm getting a fatal error when trying to run ./mautrix-imessage "The homeserver is outdated (server supports r0.6.1, but the bridge requires at least v1.1). However, when I run  curl http://localhost:8008/_synapse/admin/v1/server_version I see server version as 1.51.0. I'm not sure what the error is.

**Comment by tulir** [comment]
Synapse 1.51 is very outdated
