### ISSUE TITLE
HEIF conversion not working with Gitlab binaries

### ISSUE THREAD

**Issue by thieman** [mautrix/imessage#97]
I was excited to use the HEIF conversion from https://github.com/mautrix/imessage/pull/46, but at least with the binaries from Gitlab for amd64 I'm receiving an error on conversion stating that mautrix-imessage was compiled without libheif. I'm not sure whether it affects the other Gitlab binaries, also not sure yet what steps to take in a manual compile to make sure this works.

**Comment by thieman** [comment]
Seems like this might have been intentional, though I'm not sure why https://github.com/mautrix/imessage/commit/e3a040884bd5634b967d1bbe304e3cead30bbcc6

**Comment by tulir** [comment]
libheif has too many dependencies so not currently planning on including it in the CI binaries. `./build.sh` will automatically enable heif support if you've installed libheif with brew before compiling.

**Comment by thieman** [comment]
Can confirm I have HEIF support working after a manual compile and brew installing `libheif` first.
